<template><div><h1 id="基础属性" tabindex="-1"><a class="header-anchor" href="#基础属性"><span>基础属性</span></a></h1>
<p>这一章介绍一下Dvnge几个比较简单的基础属性使用。</p>
<h2 id="角色" tabindex="-1"><a class="header-anchor" href="#角色"><span>角色</span></a></h2>
<p>这个在之前的教程中也都有出现过，就是显示在对话框左上角的名字。</p>
<p><img src="/docsImg/helloworld.webp" alt="helloworld.webp"></p>
<p>*当然我们也可以找到css中的 <code v-pre>.角色</code> 来改变样式，不过这属于后话了。</p>
<p>在<RouteLink to="/docs/%E4%BB%80%E4%B9%88%E6%98%AF%E8%8A%82%E7%82%B9.html">节点</RouteLink>里面我们这样写角色：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">角色</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "你的角色名称"</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>我们也可以给它加上HTML标签来实现更多特殊效果，比如：</p>
<div class="language-html line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="html"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-html"><code><span class="line"><span class="line"><span style="color:#CDD6F4">角色: "</span><span style="color:#94E2D5">&#x3C;</span><span style="color:#89B4FA">span</span><span style="color:#F9E2AF"> class</span><span style="color:#94E2D5">=</span><span style="color:#A6E3A1">'red-text'</span><span style="color:#94E2D5">></span><span style="color:#CDD6F4">你的角色名称</span><span style="color:#94E2D5">&#x3C;/</span><span style="color:#89B4FA">span</span><span style="color:#94E2D5">></span><span style="color:#CDD6F4">"</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>然后再在 <code v-pre>css/样式.css</code> 文件中加上：</p>
<div class="language-css line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="css"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-css"><code><span class="line"><span class="line"><span style="color:#9399B2">.</span><span style="color:#F9E2AF">red-text</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#89B4FA">  color</span><span style="color:#94E2D5">:</span><span style="color:#9399B2"> #</span><span style="color:#CDD6F4">d03838</span><span style="color:#9399B2">;</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>或者我们直接用 <code v-pre>style</code> 写在HTML标签中：</p>
<div class="language-html line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="html"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-html"><code><span class="line"><span class="line"><span style="color:#CDD6F4">角色: "</span><span style="color:#94E2D5">&#x3C;</span><span style="color:#89B4FA">span</span><span style="color:#F9E2AF"> style</span><span style="color:#94E2D5">=</span><span style="color:#A6E3A1">'</span><span style="color:#CDD6F4">color:red;'</span><span style="color:#94E2D5">></span><span style="color:#CDD6F4">Tian</span><span style="color:#94E2D5">&#x3C;/</span><span style="color:#89B4FA">span</span><span style="color:#94E2D5">></span><span style="color:#CDD6F4">"</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>不过之后如果要复用的话，建议使用 class。</p>
<h2 id="内容" tabindex="-1"><a class="header-anchor" href="#内容"><span>内容</span></a></h2>
<p><code v-pre>内容</code> 一般情况下就是这个角色所说的话，在上图显示的白色文字就是 内容。使用代码：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">内容</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "你好，欢迎使用Dvnge。"</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><code v-pre>内容</code> 和 <code v-pre>角色</code> 一样支持HTML标签，可以自由放开想象来尝试实现各种效果~</p>
<p>比如：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#9399B2">{</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    角色</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "Tian"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    内容</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> `&#x3C;input type='text' placeholder='输入框'/>&#x3C;button onclick="alert('hello')">按钮&#x3C;/button>`</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>运行效果：</p>
<p><img src="/docsImg/content-input&amp;button.webp" alt="content-input&amp;button.webp"></p>
<h2 id="音乐" tabindex="-1"><a class="header-anchor" href="#音乐"><span>音乐</span></a></h2>
<p><code v-pre>音乐</code> 就是视觉小说的背景音乐，使用起来很简单，写上音乐文件路径就行，如：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">音乐</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "assets/music/背景音乐.mp3"</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><code v-pre>音乐</code> 默认循环播放，并且在一个节点设置之后会一直延续下去，要停止 <code v-pre>音乐</code> 需要在停止音乐的节点把路径改成 <code v-pre>null</code>，如：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#9399B2">{</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    内容</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "Hello~"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    音乐</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "assets/music/背景音乐.mp3"</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">},</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">{</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    内容</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "欢迎使用Dvnge~"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    音乐</span><span style="color:#9399B2">:</span><span style="color:#CBA6F7"> null</span><span style="color:#9399B2;font-style:italic"> // 在这个节点停止音乐</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="音效" tabindex="-1"><a class="header-anchor" href="#音效"><span>音效</span></a></h2>
<p>可以和 <code v-pre>音乐</code> 一起播放，只在设置音效的节点生效，并且只播放一次。使用方法：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">音效</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "assets/sound/打击.mp3"</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="标签" tabindex="-1"><a class="header-anchor" href="#标签"><span>标签</span></a></h2>
<p>是给节点设置一个方便人理解、记住的标签名，一般在有需要跳转到此对话时使用，设置方法：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">标签</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "标签名称"</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>具体使用示例可查看选项设置。</p>
</div></template>


