<template><div><h1 id="立绘系统" tabindex="-1"><a class="header-anchor" href="#立绘系统"><span>立绘系统</span></a></h1>
<p>本章介绍怎么使用Dvnge来操作立绘。</p>
<h2 id="立绘显示" tabindex="-1"><a class="header-anchor" href="#立绘显示"><span>立绘显示</span></a></h2>
<p>视觉小说一般都少不了立绘，要在Dvnge设置显示它很简单：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    中立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 路径</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "assets/img/立绘.png"</span><span style="color:#9399B2"> }</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>其中 <code v-pre>中立绘</code> 可以换成 <code v-pre>左立绘</code> 或 <code v-pre>右立绘</code>，也支持一次显示多个：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    左立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 路径</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> ""</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    中立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 路径</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> ""</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    右立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 路径</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> ""</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><code v-pre>立绘</code> 和 <code v-pre>音乐</code> 等一样，是会默认延续到下一节点的。</p>
<h2 id="立绘切换" tabindex="-1"><a class="header-anchor" href="#立绘切换"><span>立绘切换</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#9399B2">{</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    角色</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "Tian"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    内容</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "设置立绘"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">        中立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 路径</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "assets/img/立绘1.png"</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">    },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">},</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">{</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    角色</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "Tian"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    内容</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "默认延续上一节点设置的立绘（继续显示立绘1）"</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">},</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">{</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    角色</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "Tian"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    内容</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "切换立绘，直接更换路径即可"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">        中立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 路径</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "assets/img/立绘2.png"</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">    },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">}</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="立绘隐藏" tabindex="-1"><a class="header-anchor" href="#立绘隐藏"><span>立绘隐藏</span></a></h2>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    中立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 隐藏</span><span style="color:#9399B2">:</span><span style="color:#FAB387"> true</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">},</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>如果说要在同一个节点隐藏一个立绘显示/切换一个立绘就这样写：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#CDD6F4">立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    右立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 隐藏</span><span style="color:#9399B2">:</span><span style="color:#FAB387"> true</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    左立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 路径</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "assets/img/立绘.png"</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">},</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h2 id="变量路径" tabindex="-1"><a class="header-anchor" href="#变量路径"><span>变量路径</span></a></h2>
<p>这个一般用在玩家有多个选择，而立绘会随着玩家的选择而不同的情况下使用。比如：</p>
<p><img src="/docsImg/女or男.webp" alt="女or男.webp"></p>
<p>因为选择的不同玩家立绘也会不一样，玩家选择什么开发者是不可预测的。这个时候就需要变量路径，设置方法如下，我们以上面展示的选项为例：</p>
<div class="language-javascript line-numbers-mode line-numbers-mode" data-highlighter="prismjs" data-ext="js"><pre  class="shiki catppuccin-mocha vp-code" style="background-color:#1e1e2e;color:#cdd6f4" v-pre=" language-javascript"><code><span class="line"><span class="line"><span style="color:#9399B2">{</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    内容</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "说起来我还没有我你，你是男生还是女生？"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    选项</span><span style="color:#9399B2">:</span><span style="color:#CDD6F4"> [</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">        {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">            文本</span><span style="color:#94E2D5">:</span><span style="color:#A6E3A1"> "我是女生"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">            设置变量</span><span style="color:#94E2D5">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#A6E3A1">                "玩家性别"</span><span style="color:#94E2D5">:</span><span style="color:#A6E3A1"> "女"</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">            }</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">        },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">        {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">            文本</span><span style="color:#94E2D5">:</span><span style="color:#A6E3A1"> "我是男生"</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">            设置变量</span><span style="color:#94E2D5">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#A6E3A1">                "玩家性别"</span><span style="color:#94E2D5">:</span><span style="color:#A6E3A1"> "男"</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">            }</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">        }</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    ]</span><span style="color:#9399B2">,</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">},</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">{</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">    立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span></span></span>
<span class="line"><span class="line"><span style="color:#CDD6F4">        中立绘</span><span style="color:#9399B2">:</span><span style="color:#9399B2"> {</span><span style="color:#CDD6F4"> 路径</span><span style="color:#9399B2">:</span><span style="color:#A6E3A1"> "主控_{玩家性别}.png"</span><span style="color:#9399B2"> },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">    },</span></span></span>
<span class="line"><span class="line"><span style="color:#9399B2">},</span></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></div></template>


