import "/data/data/com.termux/files/home/dvnge-docs/node_modules/@vuepress/highlighter-helper/dist/client/styles/base.css"
import "/data/data/com.termux/files/home/dvnge-docs/node_modules/@vuepress/plugin-shiki/dist/client/styles/shiki.css"
import "/data/data/com.termux/files/home/dvnge-docs/node_modules/@vuepress/highlighter-helper/dist/client/styles/line-numbers.css"
import "/data/data/com.termux/files/home/dvnge-docs/node_modules/@vuepress/highlighter-helper/dist/client/styles/notation-highlight.css"
import "/data/data/com.termux/files/home/dvnge-docs/node_modules/@vuepress/highlighter-helper/dist/client/styles/code-block-title.css"